name: Release

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Archive
        run: |
          zip -r default_theme_src_patched.zip index.html
          mv default_theme_src_patched.zip default_theme_src_patched.bbgtheme2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: default_theme_src_patched ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: default_theme_src_patched.bbgtheme2
